### ISSUE TITLE
`oxSCIMCustomAttribute` and `oxMultivaluedAttribute` are always ignored

### ISSUE THREAD

**Issue by Yamilquery** [GuillaumeSmaha/ansible-role-gluu-configuration#5]
Hello Guillaume!

I've been using your library. Thank you very much for your effort.

Unfortunately, I'm getting some issues.

I'm trying to register some Gluu attributes, but it doesn't respect the oxSCIMCustomAttribute and oxMultivaluedAttribute values.
It always ignores my changes despite my settings, but only for those two values.

This is my config:

```
gluu_attributes:
  -
    inum: '2213'
    displayName: Last Connection Date
    gluuAttributeName: oxLastLogonTime
    gluuAttributeOrigin: gluuPerson
    gluuAttributeType: generalizedTime
    gluuAttributeViewType:
      - user
      - admin
    gluuAttributeEditType:
      - user
    gluuStatus: active
    oxAuthClaimName: lastConnectionAt
    oxMultivaluedAttribute: false
    oxSCIMCustomAttribute: false
    gluuSAML1URI: urn:mace:dir:attribute-def:oxLastLogonTime
    gluuSAML2URI: oxAttribute:210
    description: Last Connection Date
  -
    inum: 'D03E'
    displayName: Organization
    gluuAttributeName: o
    gluuAttributeOrigin: gluuPerson
    gluuAttributeType: string
    gluuAttributeViewType: admin
    gluuAttributeEditType: admin
    gluuStatus: active
    oxAuthClaimName: o
    oxMultivaluedAttribute: false
    oxSCIMCustomAttribute: true
    gluuSAML1URI: urn:mace:dir:attribute-def:o
    gluuSAML2URI: urn:oid:2.5.4.10
    description: Organization
  -
    inum: '08E2'
    displayName: Department
    gluuAttributeName: departmentNumber
    gluuAttributeOrigin: gluuPerson
    gluuAttributeType: string
    gluuAttributeViewType: admin
    gluuAttributeViewType: user
    gluuAttributeEditType: admin
    gluuStatus: active
    oxMultivaluedAttribute: true
    oxSCIMCustomAttribute: true
    gluuSAML1URI: urn:mace:dir:attribute-def:departmentNumber
    gluuSAML2URI: urn:oid:2.16.840.1.113730.3.1.2
    description: Organizational Department
  -
    inum: '6049'
    displayName: User Permission
    gluuAttributeName: role
    gluuAttributeOrigin: gluuPerson
    gluuAttributeType: string
    gluuAttributeViewType: admin
    gluuAttributeEditType: admin
    gluuStatus: active
    oxMultivaluedAttribute: true
    oxSCIMCustomAttribute: true
    gluuSAML1URI: urn:mace:dir:attribute-def:role
    gluuSAML2URI: urn:oid:1.3.6.1.4.1.48710.1.3.299
    description: User permission or role
```

And when I go to my Gluu Server, I notice that SCIM and Multi-valued aren't filled in spite of my configuration.
